CREATE TABLE ROOM(
    ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ROOM_NUMBER CHAR(2) NOT NULL UNIQUE,
    BED_INFO CHAR(2) NOT NULL
);

CREATE TABLE GUEST(
    GUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(64),
    LAST_NAME VARCHAR (64),
    EMAIL_ADDRESS VARCHAR (50),
    ADDRESS VARCHAR (200),
    COUNTRY VARCHAR (32),
    STATE VARCHAR (12),
    PHONE_NUMBER VARCHAR (24)
);

CREATE TABLE RESERVATION(
RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ROOM_ID BIGINT NOT NULL,
GUEST_ID BIGINT NOT NULL,
RES_DATE DATE
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
CREATE INDEX RESERVATION_RES_DATE ON RESERVATION(RES_DATE);